python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.0 --structure_noise_ratio 0.6 --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.2 --structure_noise_ratio 0.6  --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.4 --structure_noise_ratio 0.6  --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.6 --structure_noise_ratio 0.6  --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.8 --structure_noise_ratio 0.6  --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 1.0 --structure_noise_ratio 0.6  --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.0 --structure_noise_ratio 0.8 --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.2 --structure_noise_ratio 0.8  --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.4 --structure_noise_ratio 0.8  --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.6 --structure_noise_ratio 0.8  --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.8 --structure_noise_ratio 0.8  --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 1.0 --structure_noise_ratio 0.8  --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.0 --structure_noise_ratio 1.0 --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.2 --structure_noise_ratio 1.0  --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.4 --structure_noise_ratio 1.0  --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.6 --structure_noise_ratio 1.0  --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 0.8 --structure_noise_ratio 1.0  --if_structure True
python main_Simple_HHEA_bi_info.py --lang 'icews_yago' --cuda_num 2 --name_noise_ratio 1.0 --structure_noise_ratio 1.0  --if_structure True